#!/usr/bin/env python3
"""Orchestrator for claude-local-model swaps.

State lives at ~/.claude-local-model/. Each tier (haiku, sonnet) tracks whether
it's swapped to a local backend and which model is loaded. A LiteLLM proxy on
localhost:4000 fans requests out: swapped tiers go to the 5090, unswapped tiers
pass through to api.anthropic.com. When no tiers are swapped the proxy is shut
down and ANTHROPIC_BASE_URL is removed from ~/.claude/settings.json.
"""
from __future__ import annotations

import argparse
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

HOME = Path.home()
ROOT = HOME / ".claude-local-model"
STATE_PATH = ROOT / "state.json"
CONFIG_PATH = ROOT / "litellm.yaml"
PID_PATH = ROOT / "proxy.pid"
LOG_PATH = ROOT / "proxy.log"
SETTINGS_PATH = HOME / ".claude" / "settings.json"

PROXY_PORT = 4000
PROXY_URL = f"http://localhost:{PROXY_PORT}"

TIERS = ("haiku", "sonnet")
DEFAULT_LOCAL_MODEL = "qwen3.6-27b"
# Current Anthropic model IDs Claude Code resolves the tier aliases to; used
# when writing the passthrough entries in the LiteLLM config. Update if the
# product aliases drift.
DEFAULT_ANTHROPIC_MODEL = {
    "haiku": "claude-haiku-4-5",
    "sonnet": "claude-sonnet-4-6",
    "opus": "claude-opus-4-7",
}


def load_state() -> dict[str, Any]:
    if not STATE_PATH.exists():
        return {tier: {"swapped": False, "model": None, "upstream": None} for tier in TIERS}
    return json.loads(STATE_PATH.read_text())


def save_state(state: dict[str, Any]) -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2) + "\n")


def any_swapped(state: dict[str, Any]) -> bool:
    return any(state[tier]["swapped"] for tier in TIERS)


def render_litellm_config(state: dict[str, Any]) -> str:
    """Produce the LiteLLM YAML reflecting the current swap state.

    Swapped tiers route to the upstream llama-server recorded in state.
    Unswapped tiers (and opus, always) pass through to api.anthropic.com. The
    proxy forwards the client's own auth headers upstream via
    `forward_client_headers_to_llm_api`, so Claude Code's Claude Max OAuth
    bearer authenticates the request directly — no separate ANTHROPIC_API_KEY
    is needed. This is the only mode that works for Claude Max users without
    a paid API plan.
    """
    entries: list[str] = []
    # haiku + sonnet: follow state
    for tier in TIERS:
        s = state[tier]
        if s["swapped"]:
            entries.append(
                f"""  - model_name: "claude-{tier}*"
    litellm_params:
      model: "anthropic/{s['model']}"
      api_base: "{s['upstream']}"
      api_key: "dummy\""""
            )
        else:
            entries.append(
                f"""  - model_name: "claude-{tier}*"
    litellm_params:
      model: "anthropic/{DEFAULT_ANTHROPIC_MODEL[tier]}"
      api_base: "https://api.anthropic.com"
      api_key: "dummy\""""
            )
    # opus: always passthrough.
    entries.append(
        f"""  - model_name: "claude-opus*"
    litellm_params:
      model: "anthropic/{DEFAULT_ANTHROPIC_MODEL['opus']}"
      api_base: "https://api.anthropic.com"
      api_key: "dummy\""""
    )
    body = "\n".join(entries)
    return f"""# Generated by claude-local-model/scripts/swap.py — do not edit by hand.
model_list:
{body}

general_settings:
  # Inbound: accept anything — Claude Code authenticates via its own bearer,
  # which we don't validate; the proxy is bound to localhost so untrusted
  # callers can't reach it anyway.
  disable_auth: true
  # Forward the client's auth headers (Claude Code's OAuth bearer) to the
  # upstream LLM API. This is how Claude Max users authenticate to Anthropic
  # without a paid API key — api.anthropic.com accepts the OAuth bearer the
  # same way it does when Claude Code hits it directly. For the 5090 route
  # the forwarded headers are harmless (llama-server ignores auth).
  forward_client_headers_to_llm_api: true
"""


def write_litellm_config(state: dict[str, Any]) -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(render_litellm_config(state))


def proxy_is_running() -> bool:
    if not PID_PATH.exists():
        return False
    try:
        pid = int(PID_PATH.read_text().strip())
        os.kill(pid, 0)
        return True
    except (ValueError, ProcessLookupError, PermissionError):
        return False


def start_proxy() -> None:
    if proxy_is_running():
        # Hot-reload the config by bouncing the proxy. LiteLLM doesn't watch
        # the config file, so a restart is the reliable way to apply changes.
        stop_proxy()
    ROOT.mkdir(parents=True, exist_ok=True)
    # Use pipx/venv litellm if available, otherwise rely on PATH.
    cmd = ["litellm", "--config", str(CONFIG_PATH), "--port", str(PROXY_PORT)]
    log = open(LOG_PATH, "a")
    log.write(f"\n=== starting proxy at {time.strftime('%Y-%m-%d %H:%M:%S')} ===\n")
    log.flush()
    proc = subprocess.Popen(
        cmd,
        stdout=log,
        stderr=subprocess.STDOUT,
        start_new_session=True,  # detach from our session so Ctrl-C here doesn't kill it
    )
    PID_PATH.write_text(str(proc.pid))
    # Wait briefly for it to bind the port.
    import socket
    for _ in range(40):
        time.sleep(0.25)
        with socket.socket() as s:
            s.settimeout(0.2)
            try:
                s.connect(("127.0.0.1", PROXY_PORT))
                return
            except OSError:
                continue
    raise RuntimeError(f"LiteLLM proxy did not bind port {PROXY_PORT} within 10s — check {LOG_PATH}")


def stop_proxy() -> None:
    if not PID_PATH.exists():
        return
    try:
        pid = int(PID_PATH.read_text().strip())
        os.kill(pid, signal.SIGTERM)
        for _ in range(20):
            time.sleep(0.1)
            try:
                os.kill(pid, 0)
            except ProcessLookupError:
                break
        else:
            os.kill(pid, signal.SIGKILL)
    except (ValueError, ProcessLookupError, PermissionError):
        pass
    PID_PATH.unlink(missing_ok=True)


def update_settings_env(set_base_url: bool) -> None:
    """Flip ANTHROPIC_BASE_URL in ~/.claude/settings.json on/off.

    Leaves the rest of the file alone so we don't stomp on other config.
    """
    data: dict[str, Any] = {}
    if SETTINGS_PATH.exists():
        data = json.loads(SETTINGS_PATH.read_text())
    env = data.setdefault("env", {})
    if set_base_url:
        env["ANTHROPIC_BASE_URL"] = PROXY_URL
    else:
        env.pop("ANTHROPIC_BASE_URL", None)
        if not env:
            data.pop("env", None)
    SETTINGS_PATH.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS_PATH.write_text(json.dumps(data, indent=2) + "\n")


def apply(tier: str, target: str, model: str | None, upstream: str | None) -> dict[str, Any]:
    """Record a swap decision and reshape proxy + settings to match.

    `target` is "local" or "claude". `model` + `upstream` are required when
    target=local; caller (the skill) is responsible for having the llama-server
    running at that upstream before calling this.
    """
    assert tier in TIERS, f"tier must be one of {TIERS}"
    assert target in ("local", "claude"), "target must be 'local' or 'claude'"

    state = load_state()
    if target == "local":
        if not model or not upstream:
            raise ValueError("local swap requires model and upstream")
        state[tier] = {"swapped": True, "model": model, "upstream": upstream}
    else:
        state[tier] = {"swapped": False, "model": None, "upstream": None}
    save_state(state)
    write_litellm_config(state)

    if any_swapped(state):
        start_proxy()
        update_settings_env(set_base_url=True)
    else:
        stop_proxy()
        update_settings_env(set_base_url=False)

    return state


def status() -> dict[str, Any]:
    state = load_state()
    return {
        "state": state,
        "proxy_running": proxy_is_running(),
        "proxy_url": PROXY_URL,
        "config_path": str(CONFIG_PATH),
        "settings_has_base_url": (
            SETTINGS_PATH.exists()
            and json.loads(SETTINGS_PATH.read_text()).get("env", {}).get("ANTHROPIC_BASE_URL") == PROXY_URL
        ),
    }


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("apply", help="apply a swap decision")
    a.add_argument("--tier", required=True, choices=TIERS)
    a.add_argument("--target", required=True, choices=("local", "claude"))
    a.add_argument("--model", default=None)
    a.add_argument("--upstream", default=None)

    sub.add_parser("status")
    sub.add_parser("stop-proxy")

    args = p.parse_args(argv)
    if args.cmd == "apply":
        new_state = apply(args.tier, args.target, args.model, args.upstream)
        print(json.dumps({"state": new_state, "proxy_running": proxy_is_running()}, indent=2))
    elif args.cmd == "status":
        print(json.dumps(status(), indent=2))
    elif args.cmd == "stop-proxy":
        stop_proxy()
        print("stopped")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
